// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XoVtnLkivqkHZQ9GtS6nyrloAEhQFAc',
    appId: '1:444175837573:web:7688d969f0ae28ae3b3cec',
    messagingSenderId: '444175837573',
    projectId: 'aichatbot-99dec',
    authDomain: 'aichatbot-99dec.firebaseapp.com',
    storageBucket: 'aichatbot-99dec.firebasestorage.app',
    measurementId: 'G-R8NR1H5CP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-GXrja73tP9ftjmxE1Xmsaq2EOmgEXM',
    appId: '1:444175837573:android:3faac866b8dcaa303b3cec',
    messagingSenderId: '444175837573',
    projectId: 'aichatbot-99dec',
    storageBucket: 'aichatbot-99dec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdXt7bq-o8_WFDuluX88FEs8uMJzm2cs',
    appId: '1:444175837573:ios:ba2fc8a4e78363493b3cec',
    messagingSenderId: '444175837573',
    projectId: 'aichatbot-99dec',
    storageBucket: 'aichatbot-99dec.firebasestorage.app',
    iosBundleId: 'com.example.aichatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdXt7bq-o8_WFDuluX88FEs8uMJzm2cs',
    appId: '1:444175837573:ios:ba2fc8a4e78363493b3cec',
    messagingSenderId: '444175837573',
    projectId: 'aichatbot-99dec',
    storageBucket: 'aichatbot-99dec.firebasestorage.app',
    iosBundleId: 'com.example.aichatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XoVtnLkivqkHZQ9GtS6nyrloAEhQFAc',
    appId: '1:444175837573:web:6202f8f43b7262f33b3cec',
    messagingSenderId: '444175837573',
    projectId: 'aichatbot-99dec',
    authDomain: 'aichatbot-99dec.firebaseapp.com',
    storageBucket: 'aichatbot-99dec.firebasestorage.app',
    measurementId: 'G-NCSE9WQVWZ',
  );
}
